### ISSUE TITLE
Monitor leak

### ISSUE THREAD

**Issue by bookshelfdave** [basho/riak_repl#204] opened 2013-02-20 19:09 UTC
See: https://github.com/basho/riak_repl/blob/master/src/riak_repl2_rtsink_helper.erl#L63

**Comment by cmeiklejohn** [comment] 2014-03-24 18:45
Moved to 2.0-RC.

**Comment by cmeiklejohn** [comment] 2014-04-15 12:10
How is this a leak?  If the process goes down, the monitor automatically is disabled, no?  cc: @vinoski

**Comment by vinoski** [comment] 2014-04-15 13:17
If `write_objects/4` is called repeatedly, then a new monitor is generated for each call, even for processes already being monitored. If the processes being monitored are long-lived, then those monitors sit around taking up space, essentially leaking until the monitored processes die.

**Comment by cmeiklejohn** [comment] 2014-04-15 13:18
Agreed, but it looks like the monitor is there by design, so until this entire mechanism is refactored we can't alleviate this "leak", right?

**Comment by vinoski** [comment] 2014-04-15 13:30
Perhaps the gen_server could keep in its state a table of `{Pid,MonitorRef}` pairs to avoid creating new monitors for processes already being monitored.

BTW this module seems to be missing a `-behavior(gen_server).` attribute.

**Comment by slfritchie** [comment] 2014-04-16 07:39
I agree with Steve, I think, except that I'm puzzled about what this code is supposed to be doing.  I'm a repl newbie, sorry.  And a poolboy newbie, also.

The gen_server process running riak_repl2_rtsink_helper's code appears to be long-lived and can handle multiple `write_object()` calls which get turned into casts to this one/many/doesn't-matter long-lived gen_server.  If the poolboy worker (which is allocated by riak_repl2_rtsink_helper's code but released by riak_repl_fullsync_worker's code, odd) is also long-lived, then two things happen:
1. We leak monitors by monitoring the same poolboy pid, perhaps up to a zillion times.
2. When there's a poolboy error, we're going to get somewhere between 1 and a tsunami of 'DOWN' messages, one from each monitor.  If we leak for a really long time, e.g. millions of monitors, then the VM will lock up a scheduler thread while it traverses the dead pid's monitor list and creates 'DOWN' message tuples for each one of them and delivers them all.

IIRC #2 won't schedule the recipient PID until all of the pending monitors have generated their 'DOWN' events.  The fact that the recipient will stop after receiving the first one doesn't matter: that pid needs to be runnable before it can receive any of them.

**Comment by cmeiklejohn** [comment] 2014-04-17 14:01
OK; I'm going to take a stab at rewriting this module.

**Comment by cmeiklejohn** [comment] 2014-04-17 14:15
Addressed by #574.

**Closed as completed by cmeiklejohn** 2014-04-17 14:15 UTC
Labels: type:bug, prio:want, Kanban-Cabal-Repl
